--liquibase formatted sql
--changeset david.jandrey:1
CREATE TABLE PIZZAS_PEDIDOS (
ID          BIGINT PRIMARY KEY,
DESCRICAO VARCHAR(255),
PRECO FLOAT,
I_BORDAS   BIGINT REFERENCES PEDIDOS(ID) NOT NULL,
I_PEDIDOS  BIGINT REFERENCES PEDIDOS(ID) NOT NULL
);
--rollback DROP PIZZAS_PEDIDOS

--changeset david.jandrey:2
COMMENT ON TABLE PIZZAS_PEDIDOS IS 'Produtos';
COMMENT ON COLUMN PIZZAS_PEDIDOS.ID IS 'Identificador da produto';
COMMENT ON COLUMN PIZZAS_PEDIDOS.DESCRICAO IS 'Descrição';
COMMENT ON COLUMN PIZZAS_PEDIDOS.PRECO IS 'valor';
COMMENT ON COLUMN PIZZAS_PEDIDOS.I_BORDAS IS 'codigo da borda';
COMMENT ON COLUMN PIZZAS_PEDIDOS.I_PEDIDOS IS 'codigo do pedido';

--changeset david.jandrey:3
CREATE SEQUENCE SEQ_PIZZAS_PEDIDOS;
--rollback DROP SEQ_PIZZAS_PEDIDOS